# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

definitions:
  caches:
    node-modules: digito-ui/node_modules
docker: true
common:
    - &setDockerTag
      step:
        name: set-version
        script:
          - export TAG="$BITBUCKET_BRANCH"-"$BITBUCKET_BUILD_NUMBER"
          - echo -n $TAG > docker-tag.txt
        artifacts:
          - docker-tag.txt
    - &apiBuildStep
      step: 
        name: api-build
        image: python:3.7.2
        caches:
          - pip
        script:
          - cd digito-api
          - pip install -r requirements.txt
          - python -m nose2
    - &uiBuildStep
      step: 
        name: ui-build
        image: node:11.14.0
        caches:
          - node-modules
        script:
          - cd digito-ui
          - npm install
          - npm test src
    - &apiDockerPushStep
      step:
        name: api-docker-push
        image: docker:stable
        script:
          - echo "Exporting tag from " `pwd`/docker-tag.txt
          - export VERSION_TAG=`cat docker-tag.txt`
          - cd digito-api
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t jtalk/digito-api:$VERSION_TAG .
          - docker push jtalk/digito-api:$VERSION_TAG
          - docker tag jtalk/digito-api:$VERSION_TAG jtalk/digito-api:latest
          - docker push jtalk/digito-api:latest
        services:
          - docker
    - &uiDockerPushStep
      step:
        name: ui-docker-push
        image: docker:stable
        script:
          - echo "Exporting tag from " `pwd`/docker-tag.txt
          - export VERSION_TAG=`cat docker-tag.txt`
          - cd digito-ui
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t jtalk/digito-ui:$VERSION_TAG --build-arg PREBUILT=0 .
          - docker push jtalk/digito-ui:$VERSION_TAG
          - docker tag jtalk/digito-ui:$VERSION_TAG jtalk/digito-ui:latest
          - docker push jtalk/digito-ui:latest
        services:
          - docker
pipelines:
  default:
    - parallel:
       - *apiBuildStep
       - *uiBuildStep
  branches:
    master:
        - parallel:
          - *apiBuildStep
          - *uiBuildStep
        - *setDockerTag
        - parallel:
          - *apiDockerPushStep
          - *uiDockerPushStep
        - parallel:
          - step:
             name: deploy-api
             deployment: production
             script:
               - echo "Exporting tag from " `pwd`/docker-tag.txt
               - export VERSION_TAG=`cat docker-tag.txt`
               - ssh root@digito.jtalk.me "docker stop digito-api; docker run -d --rm --name digito-api -p 8080:80 -e UI_LOCATION=http://digito.jtalk.me jtalk:digito-api:$VERSION_TAG"
          - step:
              name: deploy-ui
              deployment: production
              script:
                - echo "Exporting tag from " `pwd`/docker-tag.txt
                - export VERSION_TAG=`cat docker-tag.txt`
                - ssh root@digito.jtalk.me "docker stop digito-ui; docker run -d --rm --name digito-ui -p 80:80 -e REACT_APP_API_LOCATION=http://digito.jtalk.me:8080 -e NODE_ENV=production jtalk:digito-ui:$VERSION_TAG"


