# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - cd digito-api
          - pip install -r requirements.txt
          - python -m nose2
    - step:
        name: deploy-api
        script:
        - cd digito-api
        - zip -r digito-api.zip . -x tests
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.9
          variables:
            AWS_ACCESS_KEY_ID: 'AKIA4P6XCSJNYSD2H2RA'
            AWS_SECRET_ACCESS_KEY: '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'
            AWS_DEFAULT_REGION: 'eu-west-2'
            APPLICATION_NAME: 'digito'
            ENVIRONMENT_NAME: 'api-prod'
            ZIP_FILE: 'digito-api.zip'

