# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

definitions:
  caches:
    node-modules: digito-ui/node_modules
common:
    - &apiBuildStep 
      step:
        name: api-build
        image: python:3.7.2
        caches:
        - pip
        script:
          - cd digito-api
          - pip install -r requirements.txt
          - python -m nose2
    - &uiBuildStep
      step:
        name: ui-build
        image: node:11.14.0
        caches:
        - node-modules
        script:
        - cd digito-ui
        - npm install
        - npm test src
pipelines:
  default:
    - parallel:
       - *apiBuildStep
       - *uiBuildStep
  branches:
    master:
        - *apiBuildStep
        - *uiBuildStep
        - step:
            name: deploy
            deployment: production
            image: kramos/alpine-zip:latest
            script:
            - cd digito-ui
            - zip -r digito-ui.zip . -x **.test.js
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.9
              variables:
                AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY'
                AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_KEY'
                AWS_DEFAULT_REGION: 'eu-west-2'
                APPLICATION_NAME: 'digito'
                ENVIRONMENT_NAME: 'ui-prod'
                ZIP_FILE: 'digito-ui.zip'
                S3_BUCKET: 'elasticbeanstalk-eu-west-2-858907644507' 
                VERSION_LABEL: 'digito-ui-${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT:0:8}'
            - cd ../digito-api
            - zip -r digito-api.zip . -x tests
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.9
              variables:
                AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY'
                AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_KEY'
                AWS_DEFAULT_REGION: 'eu-west-2'
                APPLICATION_NAME: 'digito'
                ENVIRONMENT_NAME: 'api-prod'
                ZIP_FILE: 'digito-api.zip'
                S3_BUCKET: 'elasticbeanstalk-eu-west-2-858907644507' 
                VERSION_LABEL: 'digito-api-${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT:0:8}'

