apiVersion: apps/v1
kind: Deployment
metadata:
  name: digito-ui
  labels:
    app: digito
    type: ui
spec:
  selector:
    matchLabels:
      app: digito
      type: ui
  replicas: 2
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: digito
        type: ui
    spec:
      containers:
        - name: digito-ui
          image: jtalk/digito-ui:[[IMAGE_TAG]]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: digito-ui-config
                optional: no
          startupProbe:
            periodSeconds: 5
            failureThreshold: 6
            httpGet:
              path: /health
              port: http
          livenessProbe:
            failureThreshold: 1
            httpGet: 
              path: /health
              port: http
