apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: digito-ui
  labels:
    app: digito-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - host: digito.jtalk.me
      http:
        paths:
        - path: /(.*)
          backend:
            serviceName: digito-ui
            servicePort: 80