apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: digito-ui
  labels:
    app: digito
    type: ui
  annotations:
    nginx.org/rewrites: "serviceName=digito-ui rewrite=/app;"

spec:
  rules:
    - host: digito2.jtalk.me
      http:
        paths:
        - path: /app
          backend:
            serviceName: digito-ui
            servicePort: 80
    - host: digito.jtalk.me
      http:
        paths:
        - path: /app
          backend:
            serviceName: digito-ui
            servicePort: 80