{{- define "digito.container.probe" }}
httpGet:
  port: {{ required "Probe port is required" .port }}
  path: {{ required "Probe path is required" .path | quote }}
  scheme: HTTP
{{- if hasKey . "successThreshold" }}
successThreshold: {{ .successThreshold }}
{{- end }}
{{- if hasKey . "failureThreshold" }}
failureThreshold: {{ .failureThreshold }}
{{- end }}
{{- if hasKey . "periodSeconds" }}
periodSeconds: {{ .periodSeconds }}
{{- end }}
{{- if hasKey . "timeoutSeconds" }}
timeoutSeconds: {{ .timeoutSeconds }}
{{- end }}
{{- end }}

{{- define "digito.container.probes" }}
{{- if hasKey .probes "startup" }}
startupProbe:
  {{- include "digito.container.probe" (merge (dict) .probes.startup (dict "port" .port "path" .probes.liveness.path)) | indent 2 }}
{{- end }}
{{- if hasKey .probes "liveness" }}
livenessProbe:
  {{- include "digito.container.probe" (merge (dict) .probes.liveness (dict "port" .port) ) | indent 2 }}
{{- end }}
{{- if hasKey .probes "readiness" }}
readinessProbe:
  {{- include "digito.container.probe" (merge (dict) .probes.readiness (dict "port" .port) ) | indent 2 }}
{{- end }}
{{- end }}