name: digito
domains:
  - digito.jtalk.me
basePath: ""

ui:
  type: ui
  name: digito-ui
  service:
    port: 80
  deployment:
    port: 80
    image:
      name: jtalk/digito-ui
    replicas: 2
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    affinity:
      weight: 100
      topologyKey: kubernetes.io/hostname
    probes:
      startup:
        periodSeconds: 5
        failureThreshold: 6
      liveness:
        path: /
        failureThreshold: 2
    resources:
      limits:
        memory: 80M
      requests:
        cpu: 50m
        memory: 80M

api:
  type: api
  name: digito-api
  basePath: /api
  cors:
    localhostPort: 3000
  service:
    port: 80
  deployment:
    port: 80
    image:
      name: jtalk/digito-api
    replicas: 1
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    affinity:
      weight: 100
      topologyKey: kubernetes.io/hostname
    probes:
      startup:
        periodSeconds: 5
        failureThreshold: 3
        timeoutSeconds: 3
      liveness:
        path: /health
        failureThreshold: 1
        timeoutSeconds: 3
      readiness:
        path: /readiness
        failureThreshold: 1
        timeoutSeconds: 1
    resources:
      limits:
        memory: 120M
      requests:
        cpu: 200m
        memory: 120M

serving:
  type: serving
  name: digito-serving
  service:
    port: 80
  deployment:
    port: 80
    image:
      name: jtalk/digito-serving
    replicas: 1
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    affinity:
      weight: 100
      topologyKey: kubernetes.io/hostname
    probes:
      startup:
        periodSeconds: 5
        failureThreshold: 3
        timeoutSeconds: 5
      liveness:
        path: /v1/models/model
        failureThreshold: 1
        timeoutSeconds: 1
    resources:
      limits:
        memory: 90M
      requests:
        cpu: 200m
        memory: 90M
