apiVersion: apps/v1
kind: Deployment
metadata:
  name: digito-api
  labels:
    app: digito
    type: api
spec:
  selector:
    matchLabels:
      app: digito
      type: api
  replicas: 1
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: digito
        type: api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: digito
                    type: api
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: digito-api
          image: jtalk/digito-api:[[IMAGE_TAG]]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: digito-api-config
                optional: no
          resources:
            limits:
              memory: 500M
            requests:
              cpu: 100m
              memory: 500M
          startupProbe:
            periodSeconds: 10
            failureThreshold: 6
            httpGet:
              path: /health
              port: 80
          livenessProbe:
            failureThreshold: 1
            timeoutSeconds: 5
            httpGet: 
              path: /health
              port: 80
