apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digito-api
  labels:
    app: digito-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  tls:
    - hosts:
      - digito.jtalk.me
      secretName: digito-certificate
  rules:
    - host: digito.jtalk.me
      http:
        paths:
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: digito-api
              port:
                number: 80
