apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: digito-api
  labels:
    app: digito
    type: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: digito2.jtalk.me
      http:
        paths:
        - path: /api
          backend:
            serviceName: digito-api
            servicePort: 80