apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: digito-api
  labels:
    app: digito-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  rules:
    - host: digito.jtalk.me
      http:
        paths:
        - path: /api(/|$)(.*)
          backend:
            serviceName: digito-api
            servicePort: 80