name: Digito UI

on: [push]

env:
  DOCKER_IMAGE: jtalk/digito-ui
  NODE_VERSION: 12.x
  NODE_ENV: production
  CI: true
  
jobs:
  build-release:
    name: Build and Release to Docker
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: ''
      NODE_ENV: production
      REACT_APP_API_LOCATION: /api
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.JS ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Test UI
      working-directory: digito-ui
      env:
        NODE_ENV: development
      run: |
        npm ci
        npm test src/
    - name: Build UI
      working-directory: digito-ui
      run: |
        npm ci
        npm run build
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: digito-ui
        repository: ${{ env.UI_DOCKER_IMAGE_PREFIX }}
        tags: ${{ github.sha }}
        tag_with_ref: true
        tag_with_sha: false
        push: true
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-release
    if: github.ref == 'refs/heads/master'
    env:
      KUBE_NS: digito
    steps:
      - uses: actions/checkout@v1
      - name: Authenticate with the cluster
        uses: Azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.CLUSTER_URL }}
          k8s-secret: ${{ secrets.CLUSTER_ACCOUNT_SECRET }}
      - name: Deploy to Kubernetes
        uses: jtalk/k8s-deploy@v2
        with:
          namespace: digito
          manifests: |
            digito-ui/deploy/deployment.yml
            digito-ui/deploy/service.yml
            digito-ui/deploy/ingress.yml
          images: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
  verify:
    name: Verify deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify the healthcheck URL
        run: |
          curl --fail https://digito.jtalk.me/
        














