name: Digito UI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.JS ${{ env.NODE }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Build UI
      working-directory: digito-ui
      env:
        CI: true
      run: |
        npm ci
        npm run build
        npm test src/
    - name: Upload UI build
      uses: actions/upload-artifact@v1
      with:
        name: ui-build
        path: digito-ui/build
  release-docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_IMAGE: jtalk/digito-ui
      DOCKER_BUILD_TAG: jtalk/digito-ui
      DOCKER_REF_TAG: jtalk/digito-ui:$GITHUB_REF
    steps:
      - uses: actions/checkout@v1
      - name: Download built app
        uses: actions/download-artifact@v1
        with:
          name: ui-build
          path: digito-ui/build
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        working-directory: digito-ui
        run: |
          docker build -t "$DOCKER_IMAGE:$GITHUB_SHA" .
      - name: Push current artefact
        run: |
          docker push $DOCKER_BUILD_TAG
      - name: Push branch artefact
        if: github.ref != null
        run: |
          export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:$BRANCH_NAME"
          docker push "$DOCKER_IMAGE:$BRANCH_NAME"
      - name: Push as current
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:latest"
          docker push "$DOCKER_IMAGE:latest"
        
        














