name: Digito API

on: [push]

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    env:
      DOCKER_IMAGE: jtalk/digito-api
      DOCKER_BUILD_TAG: jtalk/digito-api
      DOCKER_REF_TAG: jtalk/digito-api:$GITHUB_REF
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Build app
        working-directory: digito-api
        run: |
          pip install --upgrade pip
          pip install nose2
          python -m venv --system-site-packages .env
          source .env/bin/activate
          pip install -I -r requirements.txt
          python -m nose2
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        working-directory: digito-api
        run: |
          docker build -t "$DOCKER_IMAGE:$GITHUB_SHA" .
      - name: Push current artefact
        run: |
          docker push $DOCKER_BUILD_TAG
      - name: Push branch artefact
        if: github.ref != null
        run: |
          export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:$BRANCH_NAME"
          docker push "$DOCKER_IMAGE:$BRANCH_NAME"
      - name: Push as current
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:latest"
          docker push "$DOCKER_IMAGE:latest"
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-release
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Load Kubernetes config
        uses: digitalocean/action-doctl@v1.6.0
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show ${{ secrets.DO_K8S_CLUSTER_NAME }} > $GITHUB_WORKSPACE/.kubeconfig
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          namespace: digito
          manifests: |
            digito-api/deploy/deployment.yml
            digito-api/deploy/service.yml
            digito-api/deploy/ingress.yml
  verify:
    name: Verify deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify the healthcheck URL
        run: |
          RESULT=$(curl http://digito2.jtalk.me/api/health)
          [ "$RESULT" == "OK" ]
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
     
