name: Digito API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Build app
      working-directory: digito-api
      run: |
        pip install nose2
        python -m venv --system-site-packages .env
        source .env/bin/activate
        pip install -I -r requirements.txt
        python -m nose2
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: api-env
        path: digito-api/.env
  release-docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_IMAGE: jtalk/digito-api
      DOCKER_BUILD_TAG: jtalk/digito-api
      DOCKER_REF_TAG: jtalk/digito-api:$GITHUB_REF
    steps:
      - uses: actions/checkout@v1
      - name: Download built app
        uses: actions/download-artifact@v1
        with:
          name: api-env
          path: digito-api/.env
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        working-directory: digito-api
        run: |
          docker build -t "$DOCKER_IMAGE:$GITHUB_SHA" .
      - name: Push current artefact
        run: |
          docker push $DOCKER_BUILD_TAG
      - name: Push branch artefact
        if: github.ref != null
        run: |
          export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:$BRANCH_NAME"
          docker push "$DOCKER_IMAGE:$BRANCH_NAME"
      - name: Push as current
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:current"
          docker push "$DOCKER_IMAGE:current"
        
        
        
        
        
        
        
        
        
        
        
        
        
     
