name: Digito API

on: [push]

env:
  DOCKER_IMAGE: jtalk/digito-api
  PYTHON_VERSION: 3.7
  
jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build app
        working-directory: digito-api
        run: |
          pip install --upgrade pip
          python -m venv .env
          source .env/bin/activate
          pip install -I -r requirements-dev.txt
          python -m nose2 tests
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: digito-api
          repository: ${{ env.DOCKER_IMAGE }}
          tags: ${{ github.sha }}
          tag_with_ref: true
          tag_with_sha: false
          push: true
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
   
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-release
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Authenticate with the cluster
        uses: Azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.CLUSTER_URL }}
          k8s-secret: ${{ secrets.CLUSTER_ACCOUNT_SECRET }}
      - name: Deploy API to Kubernetes
        uses: jtalk/k8s-deploy@v2
        with:
          namespace: digito
          manifests: |
            digito-api/deploy/deployment.yml
            digito-api/deploy/service.yml
            digito-api/deploy/ingress.yml
          images: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
    
  verify:
    name: Verify deployment
    runs-on: ubuntu-latest
    needs: deploy
    env:
      API_URL: https://digito.jtalk.me/api
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Verify the deployment
        working-directory: digito-api
        run: |
          pip install -r requirements-dev.txt
          python -m nose2 postdeploy
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
     
